version: '3.1'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data
  backend:
    build: ./
    restart: always
    ports:
      - 5000:5000
  frontend:
    build: ./front
    ports:
      - 3000:3000
volumes:
  db:
    driver: local